[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "NODE_ENV=production node cluster.js"
healthcheckPath = "/health/ready"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "speekeasy"

[services.scaling]
minInstances = 1
maxInstances = 4
